### ISSUE TITLE
the toggle option in video settings doesnt seem to work.

### ISSUE THREAD

**Issue by crg-mad** [DeeChael/Concentration#10] opened 2024-06-21 05:19 UTC
its probably an incompatibility with reese's sodium options or sodium extra
![image](https://github.com/DeeChael/Concentration/assets/141097656/b1ade64f-d293-4786-bb0b-164924948fa9)

**Comment by DeeChael** [comment] 2024-06-21 05:27
i'll check it later

**Comment by DeeChael** [comment] 2024-06-21 05:30
tested, i think the problem is caused by Sodium Extra as it modify the options, I'll fix it later

**Comment by DeeChael** [comment] 2024-06-21 06:11
Fixed in 1.1.2

**Comment by DeeChael** [comment] 2024-06-21 06:12
Screenshot here
![image](https://github.com/DeeChael/Concentration/assets/63186003/14fef109-2f92-4186-9a1b-875046f0451a)

**Closed as completed by DeeChael** 2024-06-21 06:11 UTC
